### ISSUE TITLE
Regarding Liquidations: return all positions and bids for each market 

### ISSUE THREAD

**Issue by bowtiedpyro** [honey-protocol/honey-sdk#28]
In the Liquidation page we currently display all the markets - however, the TVL is only showing for the active market. 
This should be for each market. See screenshot below:

See TVL
![Screenshot 2022-11-30 at 15 46 04](https://user-images.githubusercontent.com/101187520/204826579-2f521cdf-7a9e-4afc-bea0-61fa57eddf0b.png)

See open positions
![Screenshot 2022-11-30 at 15 47 06](https://user-images.githubusercontent.com/101187520/204827115-44dcd21c-9903-49ee-a4b0-08481a817c56.png)

Now if the users clicks on say, the Pesky market - the Pesky liquidations get rendered, however - we want to be able to render this data without the user having to click on the market. 

The SDK function that goes about this data fetching is useAllPositions()

```js
  const { ...status } = useAllPositions(
    sdkConfig.saberHqConnection,
    sdkConfig.sdkWallet,
    sdkConfig.honeyId,
    currentMarketId,
    network == 'devnet' ? true : false
  );
  ```

**Comment by BowTiedHeron** [comment]
also only debt is shown for selected market
the issue is that its not able to fetch all obligations of all markets at the same time as it needs a market ID right?

**Comment by tomjpandolfi** [comment]
Completed by Pyro
